### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gowthams96**

### CODE REVIEW

**Comment by gowthams96** [comment]
Merge Request for BA820

**Review by gowthams96 — COMMENTED** [review]
Upload

**Review by elhamod — CHANGES_REQUESTED** [review]
Please put the files in properly named directory (e.g. assignments/assignment2)

Thank you!

**Comment by gowthams96** [comment]
Added the file inside Assignment/Assignment2 folder and deleted the csv file from the root folder

**Comment by elhamod** [comment]
Approved. Thank you!


Mohannad Elhamod

Clinical Assistant Professor
Questrom School of Business | Boston University

________________________________

**Pull request merged**
